### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [mikaelstaldal/DJDPlayer#1]
Would you consider publishing the `.apk` here at Github (best on the `releases/` so one can easily see when it's updated), so folks without access to _Google Play Store_ can get it? Thanks in advance!

**Comment by mikaelstaldal** [comment]
Sure, done.

**Comment by IzzySoft** [comment]
Great – thanks a lot! You can also find it [here](https://android.izzysoft.de/repo) from now on (updates taken from Github automatically as long as you publish them here :)
